### ISSUE TITLE
Getting and setting bucket type properties

### ISSUE THREAD

**Issue by brianedgerton** [basho/riak-nodejs-client#101]
Hey guys,

We are working on implementing this lib as the underlying Riak driver for a library we use internally called [Riaktive](https://github.com/LeanKit-Labs/riaktive). In looking through the source, we see operations for getting and setting bucket type properties, but they are not yet exposed on the client object. Do you have a timeframe for when this might be available or is there any way we could help get this implemented? Are you just waiting on more test coverage?

Thanks!

**Comment by lukebakken** [comment]
I just forgot to add it to the client object when I added the command. Please feel free to add it in a similar manner to [`fetchBucketProps`](https://github.com/basho/riak-nodejs-client/blob/master/lib/client.js#L149-L158) and open a PR. Thanks!

**Comment by brianedgerton** [comment]
Will do.

![image](https://cloud.githubusercontent.com/assets/301175/10491103/aad610f2-7272-11e5-8422-196195cc90e5.png)
