### ISSUE TITLE
Improve load balancing strategy [JIRA: CLIENTS-663]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-nodejs-client#107]
A `riak-nodejs-client` user has noted a scenario in which one node has 2x the network traffic of the other nodes in the cluster. My initial theory is that a slow node is causing commands to "pile up" on this node.

More information needed:
* `riak-debug` output from slow and normal node
* A description of the commands being sent to the cluster - % that are read, % write, and if there are keys more frequently accessed than others

Proposed solution: in the default node manager, take the current # of executing commands on a node into account when selecting a node for the next command. Try to keep the execution # the same or close to it for all nodes.

**Comment by lukebakken** [comment]
@drewkerrigan

**Comment by lukebakken** [comment]
create jira issue

**Comment by DSomogyi** [comment]
create jira issue
