### ISSUE TITLE
remove 1.9.0 and 1.9.1 from npm [JIRA: CLIENTS-706]

### ISSUE THREAD

**Issue by mogadanez** [basho/riak-nodejs-client#127]
Since it latest versions in 1.x. release 1.9.1 is installed when do `npm install`

scenario:
* I installed lib time ago as `npm install basho-riak-client@latest`
* in package.json it appears as  `"basho-riak-client": "^1.5.1",`
* now when i do npm install ( build machine do it  regulary ) i will get `bad` 1.9.1 release *silently*

need remove deprecated releases from npm or  make hotfix release in 1.xxx version

**Comment by lukebakken** [comment]
I followed the recommendation here https://docs.npmjs.com/cli/unpublish

You should have received a `WARNING` message when `1.9.1` installed noting that it was deprecated.

I just used the `npm unpublish` command to remove `1.9.0` and `1.9.1` from NPM.

Please note that the library is at version `2.1.1` now.

**Comment by mogadanez** [comment]
but it not compatible with old one, so need additional effort  to migrate

**Comment by lukebakken** [comment]
Other than the issue with `start` / `stop` and callbacks that you found in the `1.9.X` series, the version `2.X` client IS compatible.
