### ISSUE TITLE
simple script stopped to work after 1.8.1 to 1.9+  upgrade [JIRA: CLIENTS-707]

### ISSUE THREAD

**Issue by mogadanez** [basho/riak-nodejs-client#128]
```
var Riak = require('basho-riak-client');

var client =  new Riak.Client( ["localhost:8087"] );

client.listKeys( {bucket: "test-bucket", stream: false, bucketType: "test"}, function(err,data){
    if ( err )
        throw err;
    console.log( data)

})
```

now  it reports 

```
[RiakCluster] starting.
[RiakNode] (localhost:8087) starting
[RiakConnection] using cork() / uncork()
[RiakCluster] execute command: RpbListKeysReq remaining tries: 3.

test.js:26
        throw err;
        ^
No RiakNodes available to execute command.

```
As  I understand start  callback is required  now, but  then need validate that it is provided,  or implement "sync" logic inside constructor if it is not  provided

**Comment by lukebakken** [comment]
Please note my response to #127

In the next release I will require the callback argument. I don't believe it is worth the effort (or possible, perhaps) to implement synchronous behavior when this argument is not present. A pull request with tests for that would be accepted.
