### ISSUE TITLE
Start / stop callback improvements [JIRA: CLIENTS-746]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-nodejs-client#129]
See #128 

If a user does not provide the callback function to various `start` and `stop` methods, they may run into a scenario in which no connections and nodes are available when executing a command.

The user may wish to do other processing while connections are being established, and then check if the client is ready. At this point in time, they must check the state of the client to do so which may not be intuitive.
- If the user executes a command while the `RiakCluster` object is starting, an error should be returned indicating it instead of what is observed in #128 
- Provide `IsStarted` and `IsStopped` convenience boolean properties that check the node's state to provide a result

**Comment by mogadanez** [comment]
Another 5 cents:

I have a cluster with  several nodes node1.... node5
When one of the node becomes down in runtime - all works fine,  client retry another host when fail.
But on start it call callback with error.
So, by having err in callback i cannot say my cluster operational or not, i need do something like
```
new Riak.Client(...., function (err, client) {
                        if (err && ( !client.cluster || !client.cluster.state ) ) {
                         throw err ;
                        }
                        // can work `normally`
                    });  
```


not sure this is bad,  but need note it in doc probably.
In our environment we use docker  widely, and start/stop happens very often and I was catch this issue during daily backup when one one goes to down.

**Comment by lukebakken** [comment]
@mogadanez - please open that as a new issue.
