### ISSUE TITLE
Winston dependency is very outdated [JIRA: CLIENTS-756]

### ISSUE THREAD

**Issue by mogadanez** [basho/riak-nodejs-client#132]
Can it be updated or moved to peerDependencies?

**Comment by lukebakken** [comment]
@mogadanez  - Is this causing an issue for you?

Related to #115

**Comment by mogadanez** [comment]
hard to enable riak logging in our application, because its different versions of winston's and separate instances.

**Comment by lukebakken** [comment]
@mogadanez I just updated the dependency in this branch if you'd like to test:

https://github.com/basho/riak-nodejs-client/tree/fixes/lrb/connection-pool-gh-137

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak-nodejs-client/issues/132 

***[posted via JIRA by Derek Somogyi]***
