### ISSUE TITLE
Can't connect [JIRA: CLIENTS-779]

### ISSUE THREAD

**Issue by doronMendelson** [basho/riak-nodejs-client#136]
Hi,

For some reason I can't connect to Riak.

This is the connection line:
var client = new Riak.Client(['192.168.56.9:8087']);

client.ping(function(err,res){
  if(err)
    return console.log(err);
  console.log(res);
})

I keep getting this error:
No RiakNodes available to execute command.

**Comment by lukebakken** [comment]
The `Client` object's initialization is asynchronous. At the time Node.js executes the `ping()` method, the client may not be fully initialized.

Please use the last argument to the `Client` object constructor to provide a function to be used as a callback when initialization completes. See the example [here](http://docs.basho.com/riak/latest/dev/taste-of-riak/nodejs/).

If this does not resolve your issue, please re-open.
