### ISSUE TITLE
Allow user to pass in logger [JIRA: CLIENTS-789]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-nodejs-client#140]
Right now the `winston` module loaded by the Riak client is unique to the client and difficult to configure.

The top-level `Client` and `Cluster` objects should take in a pre-configured winston `logger`. If one is not specified, the default logger should be used.

http://stackoverflow.com/a/23714002

Related to #138

**Comment by flohdot** [comment]
Following/adding my support for this feature.
