### ISSUE TITLE
Riak Search, empty string "" becomes integer 0. [JIRA: CLIENTS-881]

### ISSUE THREAD

**Issue by zhaohanweng** [basho/riak-nodejs-client#160]
From the code it looks like isNaN is used to check the "" empty string, https://github.com/basho/riak-nodejs-client/blob/master/lib/commands/yokozuna/search.js#L98

But `isNaN("");        // false: the empty string is converted to 0 which is not NaN.` from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN.

**Comment by lukebakken** [comment]
Just so I understand, if a search returns a document whose value is the empty string, the value gets converted into an integer whose value is `0`?

It seems like [this check](https://github.com/basho/riak-nodejs-client/blob/master/lib/commands/ts/utils.js#L16-L22) should be used instead.
