### ISSUE TITLE
node process is still hanged after client.stop() [JIRA: CLIENTS-1073]

### ISSUE THREAD

**Issue by mstdokumaci** [basho/riak-nodejs-client#184]
If all the sockets were destroyed gracefully, node would just quit with no need to process.exit(). This is what i need for testing. I can't call process.exit() because I have other tests to run after testing Riak connectivity.

Please ensure the following information is supplied for new issues:

- [x] Riak Node.js Client version: 2.4.0
- [x] Node.js version: 7.0.0
- [x] Riak version: 2.1.4
- [x] Operating System / Distribution & Version: OSX Sierra
- [x] Riak `error.log` file, if applicable: no log
- [x] What commands were being executed during the error: client.stop()
- [x] What you *expected* to have happen: end gracefully, so i won't need process.exit()

Thank you!

**Comment by mstdokumaci** [comment]
my bad, hanging caused by something else.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
