### ISSUE TITLE
Reminder: take Riak-generated keys into account. [JIRA: CLIENTS-282]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-nodejs-client#3]
I just noticed this in the code:

https://github.com/basho/riak-nodejs-client/blob/master/lib/commands/kv/fetchvalue.js#L149

I know this is a Fetch, but it reminded me of something. We should remember to support the case where no key is passed in to a `PUT` and be sure to use the key returned from Riak in the result. This was an obscure bug found in the .NET client.

**Comment by Basho-JIRA** [comment]
Closing as the related GitHub issue is Closed. 

***[posted via JIRA by Derek Somogyi]***
