### ISSUE TITLE
Fully document setting up environment for running all tests and examples [JIRA: CLIENTS-356]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-nodejs-client#43]
Some of this is done, some not. And it's not in one place.
- Clone and build Riak devrel
- `tools/devrel/setup-dev-cluster`
- For examples, `tools/devrel/setup-examples`. Also note that some examples require leveldb backend as default. This is confusing.

**Comment by brianedgerton** [comment]
Was this ever documented anywhere?

I am neither a Riak admin nor a system admin, but I was able to get our [Riaktive](https://github.com/LeanKit-Labs/riaktive) test environment running using a Vagrant + Docker setup.

Here is the relevant Vagrantfile: https://github.com/LeanKit-Labs/riaktive/blob/master/Vagrantfile.sample

I have admittedly not dug deeply into your test suite, so there could be reasons why this approach wouldn't work, but would you guys be interested in something like that if we could make it work?

The sample file shows a single riak instance being run, but it could easily be rewritten to boot up a cluster of instances. Interestingly, it would also be easy to switch between Riak versions for testing.

Thoughts?

**Comment by lukebakken** [comment]
Hey Brian,

I haven't had time yet to document this. At this point, I use basho/riak-client-tools to configure Riak built from source with these commands:

```
git clone git://github.com/basho/riak.git
cd riak && make devrel DEVNODES=4
```

The above requires Erlang built from basho/otp

My co-worker @christophermancini has been working on various vagrant-type things for client testing and I'm sure would be glad to discuss it with you.

**Comment by lukebakken** [comment]
Feel free to follow up here with any questions you have about running the unit / integration tests for this project :smile:

**Comment by christophermancini** [comment]
Ha. Ok. I will dive into it in the morning.
