### ISSUE TITLE
Vclock buffer returned by fetchValue still points to RiakConnection internal ByteBuffer memory [JIRA: CLIENTS-368]

### ISSUE THREAD

**Issue by iproctor** [basho/riak-nodejs-client#45]
The vclock buffer from FetchValue is constructed with the non copying ByteBuffer.toBuffer method. Subsequent requests will use that same memory and overwrite the vclock. The symptom will be a garbage vclock at save time.

**Comment by lukebakken** [comment]
Docs: https://github.com/dcodeIO/ByteBuffer.js/wiki/API#bytebuffertobufferforcecopy
