### ISSUE TITLE
RiakCluster uses a global DefaultNodeManager by default [JIRA: CLIENTS-384]

### ISSUE THREAD

**Issue by iproctor** [basho/riak-nodejs-client#49]
I discovered doing a migration that RiakCluster uses a single global instance of DefaultNodeManager for the default node manager. This will cause trouble when multiple RiakClusters are instantiated since the node index inside DefaultNodeManager could end up exceeding the length of the passed in nodes array. Perhaps it would be better to instantiate a new DefaultNodeManager per RiakCluster.

**Comment by lukebakken** [comment]
@iproctor thank you for reporting this. A fix will be in version 1.1.3.
