### ISSUE TITLE
Installation warnings [JIRA: CLIENTS-386]

### ISSUE THREAD

**Issue by MrBokeh** [basho/riak-nodejs-client#51]
I am getting the Installation warnings as below:

npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
basho-riak-client@1.1.3 /usr/local/lib/node_modules/basho-riak-client
├── hashmap@2.0.3
├── linkedlist@1.0.1
├── winston@0.9.0 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, pkginfo@0.3.0, async@0.9.0, colors@1.0.3)
├── bytebuffer@3.5.4 (bufferview@1.0.1, long@2.2.3)
├── joi@6.0.8 (topo@1.0.2, isemail@1.1.1, hoek@2.12.0, moment@2.10.2)
└── protobufjs@3.8.2 (ascli@0.3.0)

**Comment by lukebakken** [comment]
It looks as though the `phonegap` module expects `colors` version `0.6.0-1`, but version `1.0.3` is installed via `basho-riak-client`.

You should be able to safely ignore these warnings. Let me know if this is causing specific issues.
