### ISSUE TITLE
Is it possible to persist fetched objects [JIRA: CLIENTS-391]

### ISSUE THREAD

**Issue by awenger** [basho/riak-nodejs-client#53]
``` ValidationError: "contentType" is not allowed. "lastModified" is not allowed. "isTombstone" is not allowed. "userMeta" is not allowed ```

```
client.fetchValue({
    bucketType: 'test',
    bucket: 'bucket',
    key: 'abc13'
}, function(err, res) {
    var val = res.values[0];

    client.storeValue(val, function(err, res) {
        console.log(err, res);
    })
})
```

**Comment by lukebakken** [comment]
Yes, please see the example here:

https://github.com/basho/riak-nodejs-client-examples/blob/master/github/issue-52/example.js

If the object is not found, a new one is created and stored.

If the object is found, its value is updated, and stored.
