### ISSUE TITLE
Client is overloading riak cluster with too many connections [JIRA: CLIENTS-420]

### ISSUE THREAD

**Issue by szarsti** [basho/riak-nodejs-client#62]
With this library you can easily overload cluster with too many concurrent requests. When that happens sometimes we have been receiving request errors 'overload' (just a string). 

Other times we were just getting socket error: This socket has been ended by the other party (this could be because of haproxy between clients and riak cluster).

It almost feels like library should have some sort of connection pool with reasonable limit of concurrent connections.

**Comment by lukebakken** [comment]
Hi Tomasz -

Please use the options available for the `RiakNode` and `RiakCluster` classes to limit connections and to enable queuing commands:

http://basho.github.io/riak-nodejs-client/classes/RiakCluster.html

http://basho.github.io/riak-nodejs-client/classes/RiakNode.html

You will create a `RiakNode` object for each node in your cluster, use those to create `RiakCluster` whose `execute()` method would then be used.

If this does not resolve your issue, please re-open this. Thanks!
