### ISSUE TITLE
Client does not connect to non-default Riak ports [JIRA: CLIENTS-421]

### ISSUE THREAD

**Issue by zerebral** [basho/riak-nodejs-client#63]
I've set up a 5 Node test cluster on my Mac using the Riak Dev Cluster project -
https://github.com/basho-labs/riak-dev-cluster/

I can verify that all nodes in the cluster are up from the riak-admin and issuing ping to each node - 

curl http://127.0.0.1:1[1-5]098/ping

[1/5]: http://127.0.0.1:11098/ping --> <stdout>
--_curl_--http://127.0.0.1:11098/ping
OK
[2/5]: http://127.0.0.1:12098/ping --> <stdout>
--_curl_--http://127.0.0.1:12098/ping
OK
[3/5]: http://127.0.0.1:13098/ping --> <stdout>
--_curl_--http://127.0.0.1:13098/ping
OK
[4/5]: http://127.0.0.1:14098/ping --> <stdout>
--_curl_--http://127.0.0.1:14098/ping
OK
[5/5]: http://127.0.0.1:15098/ping --> <stdout>
--_curl_--http://127.0.0.1:15098/ping
OK

Just wrote the first test script to ping these nodes - 
https://gist.github.com/zerebral/fd6879b2fcf5d866102d

The ping does not return when I pass in the node list.

It only works if I pass in a single node IP in the following form - 
127.0.0.1
(This works as I have a Riak node running locally on port 8098 too)

The client does not work when I append this host with a port - 
127.0.0.1:11098

If I pass in a wrong port number though its quick to return with an error -
127.0.0.1:21098

Error: No RiakNodes available to execute command.

If I pass in a node list with multiple hosts without a port number (Riak running on default ports - then things work okay)

**Comment by lukebakken** [comment]
Hi Anand - 

The list of ports you are using (`11098` .. `14098`) are `HTTP` ports on which Riak is listening. This is why your `curl` command succeeds - it communicates via `HTTP`.

All of Basho's client libraries, including Node.js, use Protocol Buffers over a TCP socket for communication with Riak. This uses a different port than `HTTP`.

These two lines in `riak-dev-cluster` set the `HTTP` and PB (protocol buffers) ports, respectively:

https://github.com/basho-labs/riak-dev-cluster/blob/master/Rakefile#L116-L117

So, your test script should use the following node settings:

```javascript
var client = new Riak.Client([
    '127.0.0.1:11087',
    '127.0.0.1:12087',
    '127.0.0.1:13087',
    '127.0.0.1:14087'
]);
```

Please re-open this issue if changing the port number does not resolve your issue. Thanks for using Riak and the Node.js client :smile:

**Comment by zerebral** [comment]
This works just fine now. :-)

On Sat, May 30, 2015 at 6:55 PM, Luke Bakken <notifications@github.com>
wrote:

> Hi Anand -
>
> The list of ports you are using (11098 .. 14098) are HTTP ports on which
> Riak is listening. This is why your curl command succeeds - it
> communicates via HTTP.
>
> All of Basho's client libraries, including Node.js, use Protocol Buffers
> over a TCP socket for communication with Riak. This uses a different port
> than HTTP.
>
> These two lines in riak-dev-cluster set the HTTP and PB (protocol
> buffers) ports, respectively:
>
>
> https://github.com/basho-labs/riak-dev-cluster/blob/master/Rakefile#L116-L117
>
> So, your test script should use the following node settings:
>
> var client = new Riak.Client([
>     '127.0.0.1:11087',
>     '127.0.0.1:12087',
>     '127.0.0.1:13087',
>     '127.0.0.1:14087'
> ]);
>
> Please re-open this issue if changing the port number does not resolve
> your issue. Thanks for using Riak and the Node.js client [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basho/riak-nodejs-client/issues/63#issuecomment-107040468>
> .
>



-- 

Regards,
Anand Mahajan
Zerebral IT Solutions Pvt Ltd.
Email : anand@zerebral.co.in
Cell : +91 9881 4741 84
Web : www.zerebral.co.in
