### ISSUE TITLE
Not found property should be consistent  [JIRA: CLIENTS-427]

### ISSUE THREAD

**Issue by Willyham** [basho/riak-nodejs-client#65]
The response from KV command 'fetchValue' contains a property `isNotFound`, whereas all fetct{CRDT} commands have a property called `notFound`.

Regardless of the underlying Riak implementation, it would be nice if the client would expose these consistently.

**Comment by lukebakken** [comment]
Thanks for reporting this @Willyham

**Comment by Willyham** [comment]
Thanks for the fast turnaround!
