### ISSUE TITLE
JSON parse fails when tombstone is returned [JIRA: CLIENTS-493]

### ISSUE THREAD

**Issue by tstonis** [basho/riak-nodejs-client#74]
I had a use case where a tombstone was returned and when setting convertToJs to true, the JSON parser fails on the buffer. This was a delete followed by a quick write. I worked around by making sure I set returnDeletedVClock to true when doing a read before the write. I will also submit a quick fix (return empty object) if you want to accept the pull request.

**Comment by mogadanez** [comment]
+1 for merge,
have same issue
