### ISSUE TITLE
cork/uncork not supported warning message. [JIRA: CLIENTS-497]

### ISSUE THREAD

**Issue by mightwork** [basho/riak-nodejs-client#77]
I am getting the following warning message each time I create a client. What does it signify and how to fix it ?
```
warn: [RiakConnection] wanted to use cork/uncork but not supported!
warn: [RiakConnection] wanted to use cork/uncork but not supported!
```

**Comment by mogadanez** [comment]
it's appears only on node.js 0.10.x

**Comment by lukebakken** [comment]
The [`cork / uncork`](https://strongloop.com/strongblog/whats-new-in-node-js-and-libuv-may-2-2013/) functions are used to batch socket writes to Riak. Older versions of Node don't support this function, as you note. We only test the client with Node.js version 0.12 and later.

I'll post an example for how you can suppress this if you need to use an older version of Node.js.

**Comment by lukebakken** [comment]
Please see the example here for using `cork: false` to suppress this warning:

https://github.com/basho/riak-nodejs-client-examples/blob/master/github/issue-77/example.js

Thanks!

**Comment by mightwork** [comment]
Thanks for the help :)
