### ISSUE TITLE
Investigate automatic conversion to JS object. [JIRA: CLIENTS-500]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-nodejs-client#78]
[This user suggestion](https://github.com/basho/riak-nodejs-client/commit/816e64b57c7d1cb4dd59c25586a83068f441c50a#commitcomment-11910891) should be investigated and implemented, if feasible.

@mogadanez - could you please clarify what you mean by this statement?

> now on call FetchValue over maps datatypes it return "application/riak_map" and attempt co convert it fails

You should not be using the `FetchValue` command to fetch a map data type. Is that what you are attempting?

**Comment by mogadanez** [comment]
initially related to: 
https://github.com/basho/yokozuna/issues/423#issuecomment-116732498
it is only way to detect that siblings on map appears

Also, actually it can be any, see( https://github.com/basho/rekon ) 
there is wide of content-types there, "text/html", "image/*",  etc.

**Comment by lukebakken** [comment]
Basically, deprecate the `convertToJs` option and use the Riak object's `Content-Type` to convert to / from JSON.
