### ISSUE TITLE
on production often get error  Socket error [JIRA: CLIENTS-506]

### ISSUE THREAD

**Issue by mogadanez** [basho/riak-nodejs-client#84]
Socket error; Error: This socket has been ended by the other party

**Comment by mogadanez** [comment]
I found difference: 
production has ELB + haproxy  in front

**Comment by lukebakken** [comment]
Hi Aleksandr -

At this time, this does not appear to be an issue related to Riak or the Node.js client. If you can provide reproduction steps without using ELB or haproxy, please feel free to re-open this issue or open a new one.

Thanks -
Luke
